CREATE TABLE IM_USER_INFO (
       ID BIGINT auto_increment NOT NULL COMMENT 'ID',
       USERNAME varchar(100) NOT NULL COMMENT '账号编码',
       PWD varchar(100) NULL COMMENT '密码',
       NAME varchar(100) NULL COMMENT '名称',
       NICK_NAME varchar(200) NULL COMMENT '昵称',
       FIRST_CHAR varchar(10) NULL COMMENT '首字母',
       AVATAR varchar(200) NULL COMMENT '头像',
       SEX INT NULL COMMENT '性别 （0保密、1男、2女）',
       AGE INT DEFAULT 0 NULL COMMENT '年龄',
       BIRTHDAY DATE NULL COMMENT '出生日期',
       SIGN varchar(500) NULL COMMENT '个性签名',
       PHONE varchar(50) NOT NULL DEFAULT '' COMMENT '手机号',
       EMAIL varchar(50) NOT NULL DEFAULT '' COMMENT '邮箱',
       AREA varchar(100) NULL COMMENT '地区',
       DEF_BELL varchar(100) NULL COMMENT '默认铃声',
       ACC_SOURCE INT DEFAULT 0 NULL COMMENT '账号创建方式(1邀请、0注册)',
       REGISTER_IP varchar(100) NULL COMMENT '注册IP',
       REGISTER_TYPE INT NOT NULL COMMENT '注册方式0 手机 1邮箱 2 密码',
       LAST_LOGIN_IP varchar(100) NULL COMMENT '最后登录IP',
       LAST_LOGIN_TIME datetime NULL COMMENT '最后登录时间',
       TERM varchar(100) NULL COMMENT '注册设备',
       STATUS INT DEFAULT 0 NULL COMMENT '账号状态 0正常 1 停用',
       CREATOR              varchar(64)           DEFAULT '' COMMENT '创建人',
       CREATE_TIME          datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '发送时间',
       UPDATER              varchar(64)           DEFAULT '' COMMENT '修改人',
       UPDATE_TIME          datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
       DELETED              bit      NOT NULL DEFAULT FALSE COMMENT '删除',
       TENANT_ID             bigint(20)  NOT NULL COMMENT '租户ID',
       CONSTRAINT USER_INFO_UNIQUE UNIQUE KEY (ACC_NO),
       CONSTRAINT USER_INFO_PK PRIMARY KEY (ID)
) COMMENT='用户信息表';

CREATE INDEX USER_INFO_NAME_IDX USING BTREE ON IM_USER_INFO (NAME);
CREATE INDEX USER_INFO_NICK_NAME_IDX USING BTREE ON IM_USER_INFO (NICK_NAME);
CREATE INDEX USER_INFO_PHONE_IDX USING BTREE ON IM_USER_INFO (PHONE);
CREATE INDEX USER_INFO_EMAIL_IDX USING BTREE ON IM_USER_INFO (EMAIL);
CREATE INDEX USER_INFO_create_time_IDX USING BTREE ON IM_USER_INFO (create_time);


CREATE TABLE IM_USER_LABEL (
    ID BIGINT auto_increment NOT NULL COMMENT 'ID',
    USER_ID BIGINT NOT NULL COMMENT '账号用户ID',
    TAG_ID BIGINT NOT NULL COMMENT '标签ID',
    CREATOR              varchar(64)           DEFAULT '' COMMENT '创建人',
    CREATE_TIME          datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '发送时间',
    UPDATER              varchar(64)           DEFAULT '' COMMENT '修改人',
    UPDATE_TIME          datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    DELETED              bit      NOT NULL DEFAULT FALSE COMMENT '删除',
    TENANT_ID             bigint(20)  NOT NULL COMMENT '租户ID',
    CONSTRAINT USER_LABEL_PK PRIMARY KEY (ID)
) COMMENT='人员分组标签表';
CREATE INDEX USER_LABEL_USER_ID_IDX USING BTREE ON IM_USER_LABEL (USER_ID);
CREATE INDEX USER_LABEL_TAG_ID_IDX USING BTREE ON IM_USER_LABEL (TAG_ID);
CREATE INDEX USER_LABEL_create_time_IDX USING BTREE ON IM_USER_LABEL (create_time);

CREATE TABLE IM_USER_TAGS (
   ID BIGINT auto_increment NOT NULL COMMENT 'ID',
   USER_ID BIGINT NOT NULL COMMENT '用户ID',
   TAG_NAME varchar(100) NOT NULL COMMENT '标签名称',
   TAG_DESC varchar(100) NULL COMMENT '标签描述',
   SORT INT NULL COMMENT '展示顺序',
   CREATOR              varchar(64)           DEFAULT '' COMMENT '创建人',
   CREATE_TIME          datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '发送时间',
   UPDATER              varchar(64)           DEFAULT '' COMMENT '修改人',
   UPDATE_TIME          datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
   DELETED              bit      NOT NULL DEFAULT FALSE COMMENT '删除',
   TENANT_ID             bigint(20)  NOT NULL COMMENT '租户ID',
   CONSTRAINT USER_TAGS_PK PRIMARY KEY (ID)
) COMMENT='用户标签库表';
CREATE INDEX USER_TAGS_USER_ID_IDX USING BTREE ON IM_USER_TAGS (USER_ID);
CREATE INDEX USER_TAGS_TAG_NAME_IDX USING BTREE ON IM_USER_TAGS (TAG_NAME);
CREATE INDEX USER_TAGS_create_time_IDX USING BTREE ON IM_USER_TAGS (create_time);

CREATE TABLE IM_USER_OP_LOGS (
      ID BIGINT auto_increment NOT NULL COMMENT 'ID',
      USER_ID BIGINT NOT NULL COMMENT '用户ID',
      OP_TYPE INT NOT NULL COMMENT '操作类型 (修改昵称，修改签名，修改基本信息，删除会话记录，关注、收藏、点赞、会话群主变更、会话设置、更换手机号、更换邮箱)',
      BIZ_ID varchar(100) NOT NULL DEFAULT '' COMMENT '业务ID',
      EVENT varchar(100) NOT NULL COMMENT '事件名称',
      REMARK varchar(500) NULL COMMENT '备注',
      CREATOR              varchar(64)           DEFAULT '' COMMENT '创建人',
      CREATE_TIME          datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '发送时间',
      UPDATER              varchar(64)           DEFAULT '' COMMENT '修改人',
      UPDATE_TIME          datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
      DELETED              bit      NOT NULL DEFAULT FALSE COMMENT '删除',
      TENANT_ID             bigint(20)  NOT NULL COMMENT '租户ID',
      CONSTRAINT USER_OP_LOGS_PK PRIMARY KEY (ID)
)
COMMENT='操作记录明细表';
CREATE INDEX USER_OP_LOGS_USER_ID_IDX USING BTREE ON IM_USER_OP_LOGS (USER_ID);
CREATE INDEX USER_OP_LOGS_BIZ_ID_IDX USING BTREE ON IM_USER_OP_LOGS (BIZ_ID);
CREATE INDEX USER_OP_LOGS_create_time_IDX USING BTREE ON IM_USER_OP_LOGS (create_time);

CREATE TABLE IM_USER_LOGIN_LOGS (
     ID BIGINT auto_increment NOT NULL COMMENT 'ID',
     USER_ID BIGINT NOT NULL COMMENT '用户ID',
     LOGIN_TYPE int NOT NULL COMMENT '登录方式 1 账号 2手机 3邮箱',
     LOGIN_TERM varchar(100) NULL COMMENT '登录终端',
     COUNTRY varchar(100) NULL COMMENT '登录国家',
     PROVINCE varchar(100) NULL COMMENT '登录省名称',
     CITY varchar(100) NULL COMMENT '登录城市名称',
     COUNTY varchar(200) NULL COMMENT '登录区县名称',
     ADDRESS varchar(300) NULL COMMENT '登录的具体地址',
     SYS_INFO varchar(100) NULL COMMENT '登录的系统信息',
     BROWSER varchar(100) NULL COMMENT '浏览器信息',
     REMARK varchar(500) NULL COMMENT '备注',
     CREATOR              varchar(64)           DEFAULT '' COMMENT '创建人',
     CREATE_TIME          datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '发送时间',
     UPDATER              varchar(64)           DEFAULT '' COMMENT '修改人',
     UPDATE_TIME          datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
     DELETED              bit      NOT NULL DEFAULT FALSE COMMENT '删除',
     TENANT_ID             bigint(20)  NOT NULL COMMENT '租户ID',
     CONSTRAINT USER_LOGIN_LOGS_PK PRIMARY KEY (ID)
) COMMENT='登录历史';
CREATE INDEX USER_LOGIN_LOGS_USER_ID_IDX USING BTREE ON IM_USER_LOGIN_LOGS (USER_ID);
CREATE INDEX USER_LOGIN_LOGS_create_time_IDX USING BTREE ON IM_USER_LOGIN_LOGS (create_time);

CREATE TABLE IM_USER_FRIENDS (
      ID BIGINT auto_increment NOT NULL COMMENT 'ID',
      USER_ID BIGINT NOT NULL COMMENT '我的账号ID',
      FRIEND_ID BIGINT NOT NULL COMMENT '好友账号ID',
      FRIEND_SOURCE INT DEFAULT 0 NOT NULL COMMENT '好友来源（0主动添加，1对方申请，2朋友推荐）',
      REC_USER_ID BIGINT NULL COMMENT '推荐人ID',
      STATUS INT DEFAULT 1 NOT NULL COMMENT '当前状态（0通过、1待通过、2拒绝、4删除、7拉黑、3临时禁用）',
      CREATOR              varchar(64)           DEFAULT '' COMMENT '创建人',
      CREATE_TIME          datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '发送时间',
      UPDATER              varchar(64)           DEFAULT '' COMMENT '修改人',
      UPDATE_TIME          datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
      DELETED              bit      NOT NULL DEFAULT FALSE COMMENT '删除',
      TENANT_ID             bigint(20)  NOT NULL COMMENT '租户ID',
      CONSTRAINT USER_FRIENDS_PK PRIMARY KEY (ID)
) COMMENT='我的好友';
CREATE INDEX USER_FRIENDS_USER_ID_IDX USING BTREE ON IM_USER_FRIENDS (USER_ID);
CREATE INDEX USER_FRIENDS_FRIEND_ID_IDX USING BTREE ON IM_USER_FRIENDS (FRIEND_ID);
CREATE INDEX USER_FRIENDS_CREATE_TIME_IDX USING BTREE ON IM_USER_FRIENDS (create_time);

CREATE TABLE IM_USER_USED_AVATAR (
      ID BIGINT auto_increment NOT NULL COMMENT 'ID',
      USER_ID BIGINT NOT NULL COMMENT '用户ID',
      AVATAR_URL varchar(200) NOT NULL COMMENT '头像URL',
      CREATOR              varchar(64)           DEFAULT '' COMMENT '创建人',
      CREATE_TIME          datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '发送时间',
      UPDATER              varchar(64)           DEFAULT '' COMMENT '修改人',
      UPDATE_TIME          datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
      DELETED              bit      NOT NULL DEFAULT FALSE COMMENT '删除',
      TENANT_ID             bigint(20)  NOT NULL COMMENT '租户ID',
      CONSTRAINT USER_USED_AVATAR_PK PRIMARY KEY (ID)
)  COMMENT='历史头像';
CREATE INDEX USER_USED_AVATAR_USER_ID_IDX USING BTREE ON IM_USER_USED_AVATAR (USER_ID);

CREATE TABLE IM_FRIEND_POST (
     ID BIGINT auto_increment NOT NULL COMMENT 'ID',
     USER_ID BIGINT NOT NULL COMMENT '用户ID',
     TITLE varchar(500) NOT NULL COMMENT '动态标题',
     CONTENT varchar(2000) NULL COMMENT '动态内容',
     STATUS INT DEFAULT 0 NULL COMMENT '(1发布、0草稿)',
     COUNTRY varchar(100) NULL COMMENT '发布时所在国家',
     PROVINCE varchar(100) NULL COMMENT '发布时所在省份',
     CITY varchar(100) NULL COMMENT '发布时所在城市',
     COUNTY varchar(200) NULL COMMENT '发布时所在区县',
     ADDRESS varchar(500) NULL COMMENT '发布时所在具体地址',
     `YEAR` INT NULL COMMENT '发布年',
     `MONTH` INT NULL COMMENT '发布月',
     `DAY` INT NULL COMMENT '发布日',
     PUB_TIME DATETIME NULL COMMENT '发布时间',
     SHOW_TO INT NULL COMMENT '谁可以看（公开、私密、部分可见，不给谁看）',
     CREATOR              varchar(64)           DEFAULT '' COMMENT '创建人',
     CREATE_TIME          datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '发送时间',
     UPDATER              varchar(64)           DEFAULT '' COMMENT '修改人',
     UPDATE_TIME          datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
     DELETED              bit      NOT NULL DEFAULT FALSE COMMENT '删除',
     TENANT_ID             bigint(20)  NOT NULL COMMENT '租户ID',
     CONSTRAINT FRIEND_POST_PK PRIMARY KEY (ID)
) COMMENT='朋友圈动态';
CREATE INDEX FRIEND_POST_USER_ID_IDX USING BTREE ON IM_FRIEND_POST (USER_ID);
CREATE INDEX FRIEND_POST_TITLE_IDX USING BTREE ON IM_FRIEND_POST (TITLE);
CREATE INDEX FRIEND_POST_PUB_TIME_IDX USING BTREE ON IM_FRIEND_POST (PUB_TIME);
CREATE INDEX FRIEND_POST_create_time_IDX USING BTREE ON IM_FRIEND_POST (create_time);

CREATE TABLE IM_FRIEND_POST_FIX_USER (
      ID BIGINT auto_increment NOT NULL COMMENT 'ID',
      USER_ID varchar(100) NOT NULL COMMENT '用户ID',
      POST_ID BIGINT NOT NULL COMMENT '朋友圈动态ID',
      `TYPE` INT NOT NULL COMMENT '(1提醒 2 可以看 3 禁止看 4 我不喜欢)',
      CREATOR              varchar(64)           DEFAULT '' COMMENT '创建人',
      CREATE_TIME          datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '发送时间',
      UPDATER              varchar(64)           DEFAULT '' COMMENT '修改人',
      UPDATE_TIME          datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
      DELETED              bit      NOT NULL DEFAULT FALSE COMMENT '删除',
      TENANT_ID             bigint(20)  NOT NULL COMMENT '租户ID',
      CONSTRAINT FRIEND_POST_FIX_USER_PK PRIMARY KEY (ID)
) COMMENT='朋友圈特定人员';
CREATE INDEX FRIEND_POST_FIX_USER_UID_IDX USING BTREE ON IM_FRIEND_POST_FIX_USER (USER_ID);
CREATE INDEX FRIEND_POST_FIX_UPOST_ID_IDX USING BTREE ON IM_FRIEND_POST_FIX_USER (POST_ID);
CREATE INDEX FRIEND_POST_FIX_USER_CTIME_IDX USING BTREE ON IM_FRIEND_POST_FIX_USER (CREATE_TIME);

CREATE TABLE IM_POST_COMMENT (
  ID BIGINT auto_increment NOT NULL COMMENT 'ID',
  USER_ID BIGINT NOT NULL COMMENT '用户ID',
  POST_ID BIGINT NOT NULL COMMENT '动态ID',
  CONTENT varchar(3000) NOT NULL COMMENT '评论内容',
  UPPER_ID BIGINT NULL COMMENT '上级评论内容的ID',
  STATUS INT DEFAULT 0 NULL COMMENT '1删除 2 取消 0 默认',
  CREATOR              varchar(64)           DEFAULT '' COMMENT '创建人',
  CREATE_TIME          datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '发送时间',
  UPDATER              varchar(64)           DEFAULT '' COMMENT '修改人',
  UPDATE_TIME          datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  DELETED              bit      NOT NULL DEFAULT FALSE COMMENT '删除',
  TENANT_ID             bigint(20)  NOT NULL COMMENT '租户ID',
  CONSTRAINT POST_COMMENT_PK PRIMARY KEY (ID)
) COMMENT='朋友圈评论列表';
CREATE INDEX POST_COMMENT_USER_ID_IDX USING BTREE ON IM_POST_COMMENT (USER_ID);
CREATE INDEX POST_COMMENT_POST_ID_IDX USING BTREE ON IM_POST_COMMENT (POST_ID);
CREATE INDEX POST_COMMENT_UPPER_ID_IDX USING BTREE ON IM_POST_COMMENT (UPPER_ID);
CREATE INDEX POST_COMMENT_CTIME_IDX USING BTREE ON IM_POST_COMMENT (CREATE_TIME);

CREATE TABLE IM_POST_LIKE (
   ID BIGINT auto_increment NOT NULL COMMENT 'ID',
   USER_ID BIGINT NOT NULL COMMENT '用户ID',
   POST_ID BIGINT NOT NULL COMMENT '动态ID',
   `TYPE` INT DEFAULT 0 NULL COMMENT '0 点赞  1 不喜欢',
   STATUS INT DEFAULT 0 NULL COMMENT '0默认 1点赞 2取消点赞',
   CREATOR              varchar(64)           DEFAULT '' COMMENT '创建人',
   CREATE_TIME          datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '发送时间',
   UPDATER              varchar(64)           DEFAULT '' COMMENT '修改人',
   UPDATE_TIME          datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
   DELETED              bit      NOT NULL DEFAULT FALSE COMMENT '删除',
   TENANT_ID             bigint(20)  NOT NULL COMMENT '租户ID',
   CONSTRAINT POST_LIKE_PK PRIMARY KEY (ID)
) COMMENT='朋友圈点赞和踩';
CREATE INDEX POST_LIKE_USER_ID_IDX USING BTREE ON IM_POST_LIKE (USER_ID);
CREATE INDEX POST_LIKE_POST_ID_IDX USING BTREE ON IM_POST_LIKE (POST_ID);
CREATE INDEX POST_LIKE_CTIME_IDX USING BTREE ON IM_POST_LIKE (CREATE_TIME);


CREATE TABLE IM_USER_FOLLOW (
     ID BIGINT auto_increment NOT NULL COMMENT 'ID',
     USER_ID BIGINT NOT NULL COMMENT '用户ID',
     FOLLOW_USER_ID BIGINT NOT NULL COMMENT '关注的好友ID',
     STATUS INT DEFAULT 0 NOT NULL COMMENT '0 关注 1 取消关注',
     CREATOR              varchar(64)           DEFAULT '' COMMENT '创建人',
     CREATE_TIME          datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '发送时间',
     UPDATER              varchar(64)           DEFAULT '' COMMENT '修改人',
     UPDATE_TIME          datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
     DELETED              bit      NOT NULL DEFAULT FALSE COMMENT '删除',
     TENANT_ID             bigint(20)  NOT NULL COMMENT '租户ID',
     CONSTRAINT USER_FOLLOW_PK PRIMARY KEY (ID)
) COMMENT='我的关注';
CREATE INDEX USER_FOLLOW_USER_ID_IDX USING BTREE ON IM_USER_FOLLOW (USER_ID);
CREATE INDEX USER_FOLLOW_FUSER_ID_IDX USING BTREE ON IM_USER_FOLLOW (FOLLOW_USER_ID);
CREATE INDEX USER_FOLLOW_CTIME_IDX USING BTREE ON IM_USER_FOLLOW (create_time);

CREATE TABLE IM_USER_FAVORITE (
   ID BIGINT auto_increment NOT NULL COMMENT 'ID',
   USER_ID BIGINT NOT NULL COMMENT '用户ID',
   `TYPE` INT NULL COMMENT '类型（1图片、0消息、2发票、3URL）',
   SEND_USER_ID BIGINT NULL COMMENT '发送人ID',
   MSG_ID BIGINT NOT NULL default 0 COMMENT '收藏的消息ID',
   CREATOR              varchar(64)           DEFAULT '' COMMENT '创建人',
   CREATE_TIME          datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '发送时间',
   UPDATER              varchar(64)           DEFAULT '' COMMENT '修改人',
   UPDATE_TIME          datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
   DELETED              bit      NOT NULL DEFAULT FALSE COMMENT '删除',
   TENANT_ID             bigint(20)  NOT NULL COMMENT '租户ID',
   CONSTRAINT USER_FAVORITE_PK PRIMARY KEY (ID)
) COMMENT='我的收藏';
CREATE INDEX USER_FAVORITE_USER_ID_IDX USING BTREE ON IM_USER_FAVORITE (USER_ID);
CREATE INDEX USER_FAVORITE_MSG_ID_IDX USING BTREE ON IM_USER_FAVORITE (MSG_ID);
CREATE INDEX USER_FAVORITE_CTIME_IDX USING BTREE ON IM_USER_FAVORITE (CREATE_TIME);

CREATE TABLE IM_ROOM_GROUP (
   ID BIGINT auto_increment NOT NULL COMMENT 'ID',
   CREATE_USER_ID BIGINT NOT NULL COMMENT '会话创建人',
   ROOM_GROUP varchar(200) NULL COMMENT '会话名称',
   CHANNEL varchar(200) NULL COMMENT '渠道，如商城、福利、掌柜、小店等业务线',
   SOURCE varchar(200) NULL COMMENT '来源，如商品、订单、活动、客服中心、反馈中心等入口',
   TERM varchar(200) NULL COMMENT '终端，如PC、手机、小程序、公众号、APP等',
   OS_TYPE varchar(200) NULL COMMENT 'ios、android、windows、macos',
   ITEM_ID varchar(64) NULL COMMENT '商品ID',
   SHOP_ID varchar(64) NULL COMMENT '店铺ID',
   ORDER_ID varchar(64) NULL COMMENT '订单ID',
   MER_ID varchar(64) NULL COMMENT '商家ID',
   RATE int NOT NULL DEFAULT 0 COMMENT '会话评分',
   `TYPE` INT DEFAULT 0 NULL COMMENT '会话类型（0 好友、1多人、2群组）',
   OWNER BIGINT NOT NULL COMMENT '当前群主',
   STATUS INT DEFAULT 0 NULL COMMENT '当前状态（0正常、1解散）',
   LASTED_MSG_ID BIGINT NULL COMMENT '最新消息ID',
   LASTED_MSG varchar(3000) NULL COMMENT '最新消息内容',
   LASTED_MSG_TIME DATETIME NULL COMMENT '最新消息时间',
   REMARK varchar(3000) NULL COMMENT '备注',
   CREATOR              varchar(64)           DEFAULT '' COMMENT '创建人',
   CREATE_TIME          datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '发送时间',
   UPDATER              varchar(64)           DEFAULT '' COMMENT '修改人',
   UPDATE_TIME          datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
   DELETED              bit      NOT NULL DEFAULT FALSE COMMENT '删除',
   TENANT_ID             bigint(20)  NOT NULL COMMENT '租户ID',
   CONSTRAINT ROOM_GROUP_PK PRIMARY KEY (ID)
) COMMENT='会话（群组）';
CREATE INDEX ROOM_GROUP_USER_ID_IDX USING BTREE ON IM_ROOM_GROUP (CREATE_USER_ID);
CREATE INDEX ROOM_GROUP_CTIME_IDX USING BTREE ON IM_ROOM_GROUP (CREATE_TIME);


CREATE TABLE IM_ROOM_MSG (
     ID BIGINT auto_increment NOT NULL COMMENT 'ID',
     ROOM_ID BIGINT NOT NULL COMMENT '会话ID',
     SEND_USER_ID BIGINT NOT NULL COMMENT '发送人ID',
     MSG_TYPE INT NOT NULL COMMENT '消息类型（0文本、1图片、2文件、3语音、4视频、5复杂类型）',
     MSG_CONTENT varchar(3000) NOT NULL COMMENT '消息内容',
     TERM varchar(100) NULL COMMENT '消息发送终端',
     STATUS INT DEFAULT 0 NULL COMMENT '消息状态0 正常 1撤回 2 删除',
     REF_MSG_ID BIGINT NULL COMMENT '引用消息ID',
     SYS_MSG_TYPE INT DEFAULT 0 NULL COMMENT '0 用户消息 1系统提示、2推荐类型的消息 3 AI消息 4 AI推荐消息 5 知识库消息',
     KNOWLEDGE_ID BIGINT DEFAULT 0 NULL COMMENT '知识库消息ID',
     RESULTS varchar(500) NULL COMMENT '交互类型消息的交互结果',
     REMARK varchar(500) NULL COMMENT '备注',
     CREATOR              varchar(64)           DEFAULT '' COMMENT '创建人',
     CREATE_TIME          datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '发送时间',
     UPDATER              varchar(64)           DEFAULT '' COMMENT '修改人',
     UPDATE_TIME          datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
     DELETED              bit      NOT NULL DEFAULT FALSE COMMENT '删除',
     TENANT_ID             bigint(20)  NOT NULL COMMENT '租户ID',
     CONSTRAINT ROOM_MSG_PK PRIMARY KEY (ID)
) COMMENT='会话消息表';
CREATE INDEX ROOM_MSG_USER_ID_IDX USING BTREE ON IM_ROOM_MSG (SEND_USER_ID);
CREATE INDEX ROOM_MSG_ROOM_ID_IDX USING BTREE ON IM_ROOM_MSG (ROOM_ID);
-- CREATE INDEX ROOM_MSG_MSG_CONTENT_IDX USING BTREE ON IM_ROOM_MSG (MSG_CONTENT);
CREATE INDEX ROOM_MSG_CREATE_TIME_IDX USING BTREE ON IM_ROOM_MSG (CREATE_TIME);


CREATE TABLE `IM_ROOM_USER` (
    ID BIGINT auto_increment NOT NULL COMMENT 'ID',
    ROOM_ID BIGINT NOT NULL COMMENT '会话ID',
    ROOM_GROUP varchar(200) NULL COMMENT '会话名称',
    ROOM_REMARK varchar(300) NULL COMMENT '会话备注',
    USER_ID BIGINT NULL COMMENT '人员ID',
    ENTRY_TYPE INT DEFAULT 1 NULL COMMENT '人员进入会话 类型（1 主动发起，2邀请）',
    INVITER BIGINT NULL COMMENT '邀请人',
    READ_MSG_ID BIGINT NULL COMMENT '已读最大消息ID',
    NICK_NAME varchar(100) NULL COMMENT '会话中的昵称',
    REMARK varchar(300) NULL COMMENT '群聊备注',
    USER_STATUS INT DEFAULT 0 NULL COMMENT '人员状态（1 剔除会话、2主动退出会话）',
    NO_DISTURBING INT DEFAULT 0 NULL COMMENT '消息免打扰',
    HIDE INT DEFAULT 0 NULL COMMENT '隐藏会话（会话列表不显示，不影响收消息）',
    `DELETE` INT NULL COMMENT '删除会话（作废当前会话，有消息进来重新生成新的回话，并不会展示已删除会话的消息）',
    STICK INT DEFAULT 0 NULL COMMENT '置顶',
    STICK_TIME DATETIME NULL COMMENT '置顶时间',
    BG_PIC varchar(200) NULL COMMENT '聊天背景图',
    FORBID_START_TIME DATETIME NULL COMMENT '禁用开始时间，临时拉黑某人的会话',
    FORBID_END_TIME DATETIME NULL COMMENT '禁用结束时间',
    ALERT INT NULL COMMENT '声音提示',
    ALERT_BELL varchar(100) NULL COMMENT '提示音',
    CALL_BELL varchar(100) NULL COMMENT '来电铃声',
    COMPLAINT varchar(1000) NULL COMMENT '投诉理由',
    CREATOR              varchar(64)           DEFAULT '' COMMENT '创建人',
    CREATE_TIME          datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '发送时间',
    UPDATER              varchar(64)           DEFAULT '' COMMENT '修改人',
    UPDATE_TIME          datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    DELETED              bit      NOT NULL DEFAULT FALSE COMMENT '删除',
    TENANT_ID             bigint(20)  NOT NULL COMMENT '租户ID',
    CONSTRAINT ROOM_USER_PK PRIMARY KEY (ID)
) COMMENT='会话人员和会话设置表';
CREATE INDEX ROOM_USER_USER_ID_IDX USING BTREE ON IM_ROOM_USER (USER_ID);
CREATE INDEX ROOM_USER_ROOM_ID_IDX USING BTREE ON IM_ROOM_USER (ROOM_ID);
CREATE INDEX ROOM_USER_NICK_NAME_IDX USING BTREE ON IM_ROOM_USER (NICK_NAME);
CREATE INDEX ROOM_USER_CREATE_TIME_IDX USING BTREE ON IM_ROOM_USER (CREATE_TIME);


-- 知识库（常用问答） knowledge_base

-- 知识库分类 knowledge_category

-- 渠道列表

-- 技能组

-- 技能组渠道关联关系

-- 技能组人员关联关系

-- 技能组会话分配策略

-- 常用话术

-- 最长使用的话术

-- 欢迎语

-- 敏感词

-- 会话小结

-- 渠道默认小结（一级 二级 三级）

-- 渠道默认欢迎语

-- 会话分配技能组规则