CREATE TABLE IF NOT EXISTS trade_order
(
    id                      bigint   NOT NULL AUTO_INCREMENT,
    `no`                      varchar(64)  NOT NULL,
    `type`                    int      NOT NULL,
    terminal                int      NOT NULL,
    user_id                 bigint   NOT NULL,
    user_ip                 varchar(64)  NOT NULL,
    user_remark             varchar(512),
    status                  int      NOT NULL,
    product_count           int      NOT NULL,
    cancel_type             int,
    remark                  varchar(512),
    comment_status          boolean default 0,
    brokerage_user_id       bigint,
    pay_status              bit      NOT NULL,
    pay_time                datetime,
    finish_time             datetime,
    cancel_time             datetime,
    total_price             int      NULL,
--     order_price             int      NULL,
    discount_price          int      NOT NULL,
    delivery_price          int      NOT NULL,
    adjust_price            int      NOT NULL,
    pay_price               int      NOT NULL,
    delivery_type           int      NOT NULL,
    pay_order_id            bigint,
    pay_channel_code        varchar(64),
--     delivery_template_id    bigint,
    logistics_id            bigint,
    logistics_no            varchar(64),
    delivery_time           datetime,
    receive_time            datetime,
    receiver_name           varchar(64)  NOT NULL,
    receiver_mobile         varchar(64)  NOT NULL,
    receiver_area_id        int      NOT NULL,
--     receiver_post_code      int,
    receiver_detail_address varchar(256)  NOT NULL,
    pick_up_store_id        long     NULL,
    pick_up_verify_code     varchar(256)  NULL,
    refund_status           int      NULL,
    refund_price            int      NULL,
--     after_sale_status       int      NULL,
    coupon_id               bigint   NOT NULL default 0,
    coupon_price            int      NOT NULL default 0,
    use_point               int      NULL,
    point_price             int      NOT NULL  default 0,
    point_activity_id   bigint      NULL,
    give_point              int      NULL,
    refund_point            int      NULL,
    vip_price               int      NULL,
    give_coupon_template_counts        varchar(512)  NULL,
    give_coupon_ids        varchar(256)  NULL,
    seckill_activity_id     long     NULL,
    bargain_activity_id     long     NULL,
    bargain_record_id       long     NULL,
    combination_activity_id long     NULL,
    combination_head_id     long     NULL,
    combination_record_id   long     NULL,
    creator                 varchar(64)           DEFAULT '',
    create_time             datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updater                 varchar(64)           DEFAULT '',
    update_time             datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted                 bit      NOT NULL DEFAULT FALSE,
    tenant_id bigint not null default '0',
    PRIMARY KEY (id)
    ) COMMENT '交易订单表';


CREATE TABLE IF NOT EXISTS trade_order_item
(
    id                bigint   NOT NULL AUTO_INCREMENT,
    user_id           bigint   NOT NULL,
    order_id          bigint   NOT NULL,
    cart_id           int      NULL,
    spu_id            bigint   NOT NULL,
    spu_name          varchar(256)  NOT NULL,
    sku_id            bigint   NOT NULL,
    properties        varchar(512),
    pic_url           varchar(256),
    count             int      NOT NULL,
    comment_status    boolean  NULL,
    price             int      NOT NULL,
    discount_price    int      NOT NULL,
    delivery_price    int      NULL default 0,
    adjust_price      int      NULL default 0,
    pay_price         int      NOT NULL,
    coupon_price      int      NULL default 0,
    point_price       int      NULL default 0,
    use_point         int      NULL default 0,
    give_point        int      NULL default 0,
    vip_price         int      NULL default 0,
    after_sale_id     long     NULL,
    after_sale_status int      NOT NULL,
    creator           varchar(64)           DEFAULT '',
    create_time       datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updater           varchar(64)           DEFAULT '',
    update_time       datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted           bit      NOT NULL DEFAULT FALSE,
    tenant_id bigint not null default '0',
    PRIMARY KEY (id)
    ) COMMENT '交易订单明细表';


CREATE TABLE IF NOT EXISTS trade_after_sale
(
    id             bigint   NOT NULL AUTO_INCREMENT,
    no             varchar(64)  NOT NULL,
    status         int      NOT NULL,
    type           int      NOT NULL,
    way            int      NOT NULL,
    user_id        bigint   NOT NULL,
    apply_reason   varchar(256)  NOT NULL,
    apply_description varchar(512),
    apply_pic_urls varchar(512),
    order_id       bigint   NOT NULL,
    order_no       varchar(64)  NOT NULL,
    order_item_id  bigint   NOT NULL,
    spu_id         bigint   NOT NULL,
    spu_name       varchar(256)  NOT NULL,
    sku_id         bigint   NOT NULL,
    properties     varchar(512),
    pic_url        varchar(256),
    count          int      NOT NULL,
    audit_time     varchar(64),
    audit_user_id  bigint,
    audit_reason   varchar(256),
    refund_price   int      NOT NULL,
    pay_refund_id  bigint,
    refund_time    varchar(64),
    logistics_id   bigint,
    logistics_no   varchar(64),
    delivery_time  varchar(64),
    receive_time   varchar(64),
    receive_reason varchar(512),
    creator        varchar(64)           DEFAULT '',
    create_time    datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updater        varchar(64)           DEFAULT '',
    update_time    datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted        bit      NOT NULL DEFAULT FALSE,
    tenant_id         bigint   NOT NULL DEFAULT '0',
    PRIMARY KEY (id)
    ) COMMENT '交易售后表';

CREATE TABLE IF NOT EXISTS trade_after_sale_log
(
    id            bigint   NOT NULL AUTO_INCREMENT,
    user_id       bigint   NOT NULL,
    user_type     int      NOT NULL,
    after_sale_id bigint   NOT NULL,
    order_id      bigint   NOT NULL,
    order_item_id bigint   NOT NULL,
    before_status int,
    after_status  int      NOT NULL,
    content       varchar(512)  NOT NULL,
    creator       varchar(64)           DEFAULT '',
    create_time   datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updater       varchar(64)           DEFAULT '',
    update_time   datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted       bit      NOT NULL DEFAULT FALSE,
    PRIMARY KEY (id)
    ) COMMENT '交易售后日志';

CREATE TABLE `trade_order_log` (
   `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
   `user_id` bigint NOT NULL COMMENT '用户编号',
   `user_type` int NOT NULL default 0 COMMENT '用户类型',
   `order_id` bigint NOT NULL COMMENT '订单号',
   `before_status` int NULL COMMENT '操作前状态',
   `after_status` int NOT NULL COMMENT '操作后状态',
   `operate_type` int NOT NULL COMMENT '操作类型',
   `content` varchar(3000) NOT NULL COMMENT '订单日志信息',

   `creator` varchar(64) DEFAULT '' COMMENT '创建者',
   `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
   `updater` varchar(64) DEFAULT '' COMMENT '更新者',
   `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
   `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
   `tenant_id` bigint NOT NULL DEFAULT '0',
   PRIMARY KEY (`id`)
) COMMENT='订单日志';
CREATE TABLE IF NOT EXISTS trade_brokerage_user
(
    id                bigint   NOT NULL AUTO_INCREMENT,
    bind_user_id      bigint   NOT NULL,
    bind_user_time    varchar(64),
    brokerage_enabled bit      NOT NULL,
    brokerage_time    varchar(64),
    brokerage_price             int      NOT NULL,
    frozen_price      int      NOT NULL,
    creator           varchar(64)           DEFAULT '',
    create_time       datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updater           varchar(64)           DEFAULT '',
    update_time       datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted           bit      NOT NULL DEFAULT FALSE,
    tenant_id         bigint   NOT NULL DEFAULT '0',
    PRIMARY KEY (id)
    ) COMMENT '分销用户';
CREATE TABLE IF NOT EXISTS trade_brokerage_record
(
    id            int      NOT NULL AUTO_INCREMENT,
    user_id       bigint   NOT NULL,
    biz_id        varchar(64)  NOT NULL,
    biz_type      varchar(64)  NOT NULL,
    title         varchar(256)  NOT NULL,
    price         int      NOT NULL,
    total_price   int      NOT NULL,
    description   varchar(512)  NOT NULL,
    status        varchar(32)  NOT NULL,
    frozen_days   int      NOT NULL,
    unfreeze_time varchar(64),
    creator       varchar(64)           DEFAULT '',
    create_time   datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updater       varchar(64)           DEFAULT '',
    update_time   datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted       bit      NOT NULL DEFAULT FALSE,
    tenant_id bigint not null default '0',
    PRIMARY KEY (id)
    ) COMMENT '佣金记录';

CREATE TABLE IF NOT EXISTS trade_brokerage_withdraw
(
    id                  int      NOT NULL AUTO_INCREMENT,
    user_id             bigint   NOT NULL,
    price               int      NOT NULL,
    fee_price           int      NOT NULL,
    total_price         int      NOT NULL,
    type                varchar(32)  NOT NULL,
    name                varchar(128),
    account_no          varchar(32),
    bank_name           varchar(128),
    bank_address        varchar(256),
    account_qr_code_url varchar(128),
    status              varchar(32)  NOT NULL,
    audit_reason        varchar(256),
    audit_time          varchar(64),
    remark              varchar(512),
    creator             varchar(64)           DEFAULT '',
    create_time         datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updater             varchar(64)           DEFAULT '',
    update_time         datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted             bit      NOT NULL DEFAULT FALSE,
    tenant_id bigint not null default '0',
    PRIMARY KEY (id)
    ) COMMENT '佣金提现';

CREATE TABLE IF NOT EXISTS trade_delivery_express
(
    id          int      NOT NULL AUTO_INCREMENT,
    code        varchar(64)  NULL,
    name        varchar(128),
    logo        varchar(256)  NULL,
    sort        int      NOT NULL,
    status      int      NOT NULL,
    creator     varchar(64)           DEFAULT '',
    create_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updater     varchar(64)           DEFAULT '',
    update_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted     bit      NOT NULL DEFAULT FALSE,
    tenant_id bigint not null default '0',
    PRIMARY KEY (id)
    ) COMMENT '佣金提现';

CREATE TABLE IF NOT EXISTS trade_config (
      id BIGINT auto_increment NOT NULL,
      after_sale_refund_reasons varchar(1024) NULL COMMENT '售后的退款理由',
      after_sale_return_reasons varchar(1024) NULL COMMENT '售后的退货理由',
      delivery_express_free_enabled BIT DEFAULT 0 NULL COMMENT '是否启用全场包邮',
      delivery_express_free_price BIGINT NULL COMMENT '全场包邮的最小金额，单位：分',
      delivery_pick_up_enabled BIT DEFAULT 0 NULL COMMENT '是否开启自提',
      brokerage_enabled BIT DEFAULT 0 NULL COMMENT '是否启用分佣',
      brokerage_enabled_condition INT NULL COMMENT '分佣模式',
      brokerage_bind_mode INT NULL COMMENT '分销关系绑定模式',
      brokerage_poster_urls varchar(1024) NULL COMMENT '分销海报图地址数组',
      brokerage_first_percent INT NULL COMMENT '一级返佣比例',
      brokerage_second_percent INT NULL COMMENT '二级返佣比例',
      brokerage_withdraw_min_price INT NULL COMMENT '用户提现最低金额',
      brokerage_withdraw_fee_percent INT NULL COMMENT '用户提现手续费百分比',
      brokerage_frozen_days INT NULL COMMENT '佣金冻结时间(天)',
      brokerage_withdraw_types varchar(256) NULL COMMENT '提现方式',
      create_time DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '创建时间',
      update_time DATETIME NULL COMMENT '最后更新时间',
      creator varchar(64) NULL COMMENT '创建者',
      updater varchar(64) NULL COMMENT '更新者',
      deleted BIT DEFAULT 0 NULL COMMENT '是否删除',
    tenant_id BIGINT DEFAULT 0 NULL COMMENT '租户ID',
      CONSTRAINT trade_config_pk PRIMARY KEY (id)
)
COMMENT='交易中心配置';

CREATE TABLE IF NOT EXISTS trade_delivery_pick_up_store (
      id BIGINT auto_increment NOT NULL,
      name varchar(256) NOT NULL COMMENT '门店名称',
      introduction varchar(1024) NULL COMMENT '门店简介',
      phone varchar(100) NULL COMMENT '门店手机',
      area_id INT NULL COMMENT '区域编号',
      detail_address varchar(512) NULL COMMENT '门店详细地址',
      logo varchar(100) NULL COMMENT '门店 logo',
      opening_time DATETIME NOT NULL COMMENT '营业开始时间',
      closing_time DATETIME NOT NULL COMMENT '营业结束时间',
      latitude DOUBLE NULL COMMENT '纬度',
      longitude DOUBLE NULL COMMENT '经度',
      verify_user_ids varchar(512) NULL COMMENT '核销员工用户编号数组',
      status INT NULL COMMENT '门店状态',
      create_time DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
      update_time DATETIME NULL,
      creator varchar(100) NULL,
      updater varchar(100) NULL,
      deleted BIT DEFAULT 0 NULL COMMENT '是否删除',
      tenant_id BIGINT DEFAULT 0 NULL COMMENT '租户ID',
      CONSTRAINT trade_delivery_pick_up_store_pk PRIMARY KEY (id)
)
COMMENT='自提门店';

CREATE TABLE IF NOT EXISTS trade_delivery_express_template (
     id BIGINT auto_increment NOT NULL,
     name varchar(256) NOT NULL COMMENT '模板名称',
     charge_mode INT NULL COMMENT '配送计费方式',
     sort INT DEFAULT 10 NULL COMMENT '排序',
     create_time DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
     update_time DATETIME NULL,
     creator varchar(100) NULL,
     updater varchar(100) NULL,
     deleted BIT DEFAULT 0 NULL COMMENT '是否删除',
    tenant_id BIGINT DEFAULT 0 NULL COMMENT '租户ID',
     CONSTRAINT trade_delivery_express_template_pk PRIMARY KEY (id)
)
COMMENT='快递运费模板';

CREATE TABLE IF NOT EXISTS trade_delivery_express_template_charge (
  id BIGINT auto_increment NOT NULL,
  template_id BIGINT NOT NULL COMMENT '配送模板编号',
  area_ids text NULL COMMENT '配送区域编号列表',
    charge_mode INT NULL COMMENT '配送计费方式',
    start_count DOUBLE DEFAULT 0 NULL COMMENT '首件数量(件数,重量，或体积)',
    start_price INT DEFAULT 0 NULL COMMENT '起步价，单位：分',
    extra_count DOUBLE DEFAULT 0 NULL COMMENT '续件数量(件, 重量，或体积)',
    extra_price INT DEFAULT 0 NULL COMMENT '额外价，单位：分',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    update_time DATETIME NULL,
    creator varchar(100) NULL,
    updater varchar(100) NULL,
    deleted BIT DEFAULT 0 NULL COMMENT '是否删除',
    tenant_id BIGINT DEFAULT 0 NULL COMMENT '租户ID',
    CONSTRAINT trade_delivery_express_template_charge_pk PRIMARY KEY (id)
    )
    COMMENT='快递运费模板计费配置';

CREATE TABLE IF NOT EXISTS trade_delivery_express_template_free (
    id BIGINT auto_increment NOT NULL,
    template_id BIGINT NOT NULL COMMENT '配送模板编号',
    area_ids text NULL COMMENT '配送区域编号列表',
    free_price INT NULL COMMENT '订单总金额 > 包邮金额时，才免运费',
    free_count INT DEFAULT 0 NULL COMMENT '订单总件数 > 包邮件数时，才免运费',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    update_time DATETIME NULL,
    creator varchar(100) NULL,
    updater varchar(100) NULL,
    deleted BIT DEFAULT 0 NULL COMMENT '是否删除',
    tenant_id BIGINT DEFAULT 0 NULL COMMENT '租户ID',
    CONSTRAINT trade_delivery_express_template_free_pk PRIMARY KEY (id)
    )
    COMMENT='快递运费模板包邮配置';

CREATE TABLE IF NOT EXISTS `trade_cart` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `user_id` bigint NOT NULL COMMENT '用户ID',
  `spu_id` bigint NOT NULL COMMENT '商品 SPU 编号',
  `sku_id` bigint NOT NULL COMMENT '商品 SKU 编号',
  `count` int NOT NULL COMMENT '商品购买数量',
  `selected` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) COMMENT='购物车的商品信息';