CREATE TABLE IF NOT EXISTS pay_app (
    id bigint NOT NULL AUTO_INCREMENT,
    app_key              varchar(64)   NOT NULL,
    name              varchar(64)   NOT NULL,
    status            tinyint       NOT NULL,
    remark            varchar(255)           DEFAULT NULL,
    `order_notify_url`    varchar(1024) NOT NULL,
    `refund_notify_url` varchar(1024) NOT NULL,
    transfer_notify_url varchar(1024)  NULL,
    creator           varchar(64)            DEFAULT '',
    create_time       datetime      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updater           varchar(64)            DEFAULT '',
    update_time       datetime      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted           bit(1)        NOT NULL DEFAULT FALSE,
    tenant_id bigint not null default  '0',
    PRIMARY KEY (id)
) COMMENT = '支付应用';

CREATE TABLE IF NOT EXISTS pay_channel (
    id bigint NOT NULL AUTO_INCREMENT,
    code        varchar(32)    NOT NULL,
    status      tinyint(4)     NOT NULL,
    remark      varchar(255)            DEFAULT NULL,
    fee_rate    double         NOT NULL DEFAULT 0,
    app_id      bigint(20)     NOT NULL,
    config      varchar(10240) NOT NULL,
    creator     varchar(64)    NULL     DEFAULT '',
    create_time datetime       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updater     varchar(64)    NULL     DEFAULT '',
    update_time datetime       NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted     bit(1)         NOT NULL DEFAULT FALSE,
    tenant_id bigint not null default  '0',
    PRIMARY KEY (id)
) COMMENT = '支付渠道';

CREATE TABLE IF NOT EXISTS `pay_order` (
    id bigint NOT NULL AUTO_INCREMENT,
    `app_id`               bigint(20)    NOT NULL,
    `channel_id`           bigint(20)             DEFAULT NULL,
    `channel_code`         varchar(32)            DEFAULT NULL,
    `merchant_order_id`    varchar(64)   NOT NULL,
    `subject`              varchar(32)   NOT NULL,
    `body`                 varchar(128)  NOT NULL,
    `notify_url`           varchar(1024) NOT NULL,
    `price`                bigint(20)    NOT NULL,
    `channel_fee_rate`     double                 DEFAULT 0,
    `channel_fee_price`    bigint(20)             DEFAULT 0,
    `status`               tinyint(4)    NOT NULL,
    `user_ip`              varchar(50)   NOT NULL,
    `user_id`              bigint(20)             DEFAULT NULL,
    `user_type`            tinyint(4)             DEFAULT NULL,
    `expire_time`          timestamp   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `success_time`         datetime(0)            DEFAULT CURRENT_TIMESTAMP,
    `notify_time`          datetime(0)            DEFAULT CURRENT_TIMESTAMP,
    `extension_id` bigint(20)             DEFAULT NULL,
    `no`                   varchar(64)   NULL,
    `refund_price`         bigint(20)    NOT NULL,
    `channel_user_id`      varchar(255)           DEFAULT NULL,
    `channel_order_no`     varchar(64)            DEFAULT NULL,
    `creator`              varchar(64)            DEFAULT '',
    `create_time`          datetime(0)   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater`              varchar(64)            DEFAULT '',
    `update_time`          datetime(0)   NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted`              bit(1)        NOT NULL DEFAULT FALSE,
    tenant_id bigint not null default  '0',
    PRIMARY KEY (id)
) COMMENT = '支付订单';

CREATE TABLE IF NOT EXISTS `pay_order_extension` (
    id bigint NOT NULL AUTO_INCREMENT,
    `no`           varchar(64)         NOT NULL,
    `order_id`           bigint(20)    NOT NULL,
    `channel_id`         bigint(20)    NOT NULL,
    `channel_code`       varchar(32)   NOT NULL,
    `user_ip`            varchar(50)   NULL     DEFAULT NULL,
    `status`             tinyint(4)    NOT NULL,
    `channel_extras`     varchar(1024) NULL     DEFAULT NULL,
    `channel_error_code`  varchar(64)  NULL,
    `channel_error_msg` varchar(64)    NULL,
    `channel_notify_data` varchar(1024)  NULL,
    `creator`            varchar(64)   NULL     DEFAULT '',
    `create_time`        datetime(0)   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater`            varchar(64)   NULL     DEFAULT '',
    `update_time`        datetime(0)   NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted`            bit(1)        NOT NULL DEFAULT FALSE,
    tenant_id bigint not null default  '0',
    PRIMARY KEY (id)
) COMMENT = '支付订单拓展';

CREATE TABLE IF NOT EXISTS `pay_refund` (
    id bigint NOT NULL AUTO_INCREMENT,
    `no`           varchar(64)         NOT NULL,
    `app_id`             bigint(20)    NOT NULL,
    `channel_id`         bigint(20)    NOT NULL,
    `channel_code`       varchar(32)   NOT NULL,
    `order_id`           bigint(20)    NOT NULL,
    `order_no`           varchar(64)    NOT NULL,
    `merchant_order_id`  varchar(64)   NOT NULL,
    `merchant_refund_id` varchar(64)   NOT NULL,
    `notify_url`         varchar(1024) NOT NULL,
    `status`             tinyint(4)    NOT NULL,
    `pay_price`         bigint(20)    NOT NULL,
    `refund_price`      bigint(20)    NOT NULL,
    `reason`             varchar(256)  NOT NULL,
    `user_ip`            varchar(50)   NULL     DEFAULT NULL,
    `user_id`            bigint(20)    NULL     DEFAULT NULL,
    `user_type`          tinyint(4)    NULL     DEFAULT NULL,
    `channel_order_no`   varchar(64)   NOT NULL,
    `channel_refund_no`  varchar(64)   NULL     DEFAULT NULL,
    `success_time`       datetime(0)   NULL     DEFAULT NULL,
    `channel_error_code` varchar(128)  NULL     DEFAULT NULL,
    `channel_error_msg`  varchar(256)  NULL     DEFAULT NULL,
    `channel_notify_data` varchar(1024)  NULL,
    `creator`            varchar(64)   NULL     DEFAULT '',
    `create_time`        datetime(0)   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater`            varchar(64)   NULL     DEFAULT '',
    `update_time`        datetime(0)   NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted`            bit(1)        NOT NULL DEFAULT FALSE,
    tenant_id bigint not null default  '0',
    PRIMARY KEY (id)
) COMMENT = '退款订单';

CREATE TABLE IF NOT EXISTS `pay_notify_task` (
    id bigint NOT NULL AUTO_INCREMENT,
    `app_id`             bigint(20)    NOT NULL,
    `type`               tinyint(4)    NOT NULL,
    `data_id`           bigint(20)    NOT NULL,
    `merchant_order_id`           varchar(64)    NOT NULL,
    `merchant_refund_id`           varchar(64)   NULL,
    `merchant_transfer_id`           varchar(64)  NULL,
    `status`             tinyint(4)    NOT NULL,
    `next_notify_time`       datetime(0)   NULL     DEFAULT NULL,
    `last_execute_time`       datetime(0)   NULL     DEFAULT NULL,
    `notify_times`         int    NOT NULL,
    `max_notify_times`         int    NOT NULL,
    `notify_url`         varchar(1024) NOT NULL,
    `creator`            varchar(64)   NULL     DEFAULT '',
    `create_time`        datetime(0)   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater`            varchar(64)   NULL     DEFAULT '',
    `update_time`        datetime(0)   NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted`            bit(1)        NOT NULL DEFAULT FALSE,
    `tenant_id`           bigint(20)    NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
) COMMENT = '支付通知任务';

CREATE TABLE IF NOT EXISTS `pay_notify_log` (
    id bigint NOT NULL AUTO_INCREMENT,
    `task_id`             bigint(20)    NOT NULL,
    `notify_times`         int    NOT NULL,
    `response`         varchar(1024) NOT NULL,
    `status`             tinyint(4)    NOT NULL,
    `creator`            varchar(64)   NULL     DEFAULT '',
    `create_time`        datetime(0)   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater`            varchar(64)   NULL     DEFAULT '',
    `update_time`        datetime(0)   NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted`            bit(1)        NOT NULL DEFAULT FALSE,
    `tenant_id`           bigint(20)    NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
) COMMENT = '支付通知日志';

CREATE TABLE IF NOT EXISTS `pay_transfer` (
    id bigint NOT NULL AUTO_INCREMENT,
    `no`                   varchar(64)   NOT NULL,
    `app_id`               bigint(20)    NOT NULL,
    `channel_id`           bigint(20)    NOT NULL,
    `channel_code`         varchar(32)   NOT NULL,
    `user_id`              bigint(20)    NULL     DEFAULT NULL,
    `user_type`            tinyint(4)    NULL     DEFAULT NULL,
    `merchant_transfer_id` varchar(64)   NOT NULL,
    `price`                bigint(20)    NOT NULL,
    `subject`              varchar(256)  NOT NULL,
    `user_account`         varchar(256)  NOT NULL,
    `user_name`            varchar(64)   NULL     DEFAULT NULL,
    `status`               tinyint(4)    NOT NULL,
    `notify_url`           varchar(1024) NULL     DEFAULT NULL,
    `channel_transfer_no`  varchar(64)   NULL     DEFAULT NULL,
    `success_time`         datetime(0)   NULL     DEFAULT NULL,
    `channel_error_code`   varchar(128)  NULL     DEFAULT NULL,
    `channel_error_msg`    varchar(256)  NULL     DEFAULT NULL,
    `channel_notify_data`  varchar(1024) NULL     DEFAULT NULL,
    `channel_extras`       varchar(1024) NULL     DEFAULT NULL,
    `creator`              varchar(64)   NULL     DEFAULT '',
    `create_time`          datetime(0)   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater`              varchar(64)   NULL     DEFAULT '',
    `update_time`          datetime(0)   NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted`              bit(1)        NOT NULL DEFAULT FALSE,
    tenant_id bigint not null default  '0',
    PRIMARY KEY (id)
) COMMENT = '转账单';

CREATE TABLE IF NOT EXISTS pay_wallet_recharge (
     id BIGINT auto_increment NOT NULL,
     wallet_id BIGINT NOT NULL COMMENT '钱包编号',
     total_price FLOAT NOT NULL COMMENT '用户实际到账余额',
     pay_price FLOAT NOT NULL COMMENT '实际支付金额',
     bonus_price varchar(100) DEFAULT '0' NULL COMMENT '钱包赠送金额',
     package_id BIGINT NULL COMMENT '充值套餐编号',
     pay_status BIT DEFAULT 0 NULL COMMENT '是否已支付',
     pay_order_id BIGINT NULL COMMENT '支付订单编号',
     pay_channel_code varchar(100) NULL COMMENT '支付成功的支付渠道',
     pay_time DATETIME NOT NULL COMMENT '订单支付时间',
     pay_refund_id BIGINT NULL COMMENT '支付退款单编号',
     refund_total_price FLOAT NULL COMMENT '退款金额，包含赠送金额',
     refund_pay_price FLOAT NULL COMMENT '退款支付金额',
     refund_bonus_price FLOAT NULL COMMENT '退款钱包赠送金额',
     refund_time DATETIME NULL COMMENT '退款时间',
     refund_status INT NULL COMMENT '退款状态',
     create_time DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '创建时间',
     update_time DATETIME NULL COMMENT '最后更新时间',
     creator varchar(64) NULL COMMENT '创建者',
     updater varchar(64) NULL COMMENT '更新者',
     deleted BIT DEFAULT 0 NULL COMMENT '是否删除',
    tenant_id bigint not null default  '0',
     CONSTRAINT pay_wallet_recharge_pk PRIMARY KEY (id)
)
COMMENT='会员钱包充值';

CREATE TABLE IF NOT EXISTS pay_wallet (
      id BIGINT auto_increment NOT NULL,
      user_id BIGINT NOT NULL COMMENT '用户 id',
      user_type INT NULL COMMENT '用户类型, 预留 多商户转帐可能需要用到',
      balance bigint default 0 NULL COMMENT '余额，单位分',
      freeze_price INT NULL COMMENT '冻结金额，单位分',
      total_expense INT NULL COMMENT '累计支出，单位分',
      total_recharge INT NOT NULL COMMENT '累计充值，单位分',
      create_time DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
      update_time DATETIME NULL,
      creator varchar(100) NULL,
    updater varchar(100) NULL,
    deleted BIT DEFAULT 0 NULL COMMENT '是否删除',
    tenant_id BIGINT NOT NULL COMMENT '租户',
    CONSTRAINT pay_wallet_pk PRIMARY KEY (id)
    )
    COMMENT='会员钱包';

CREATE TABLE IF NOT EXISTS pay_wallet_recharge_package (
   id BIGINT auto_increment NOT NULL,
   name varchar(256) NOT NULL COMMENT '套餐名',
    pay_price INT NULL COMMENT '支付金额',
    bonus_price INT NULL COMMENT '赠送金额',
    status INT NOT NULL COMMENT '状态',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    update_time DATETIME NULL,
    creator varchar(100) NULL,
    updater varchar(100) NULL,
    deleted BIT DEFAULT 0 NULL COMMENT '是否删除',
    tenant_id BIGINT NOT NULL COMMENT '租户',
    CONSTRAINT pay_wallet_recharge_package_pk PRIMARY KEY (id)
    )
    COMMENT='会员钱包充值套餐';
CREATE TABLE `pay_wallet_transaction` (
      `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
      `no` varchar(256) NOT NULL COMMENT '流水号',
      `wallet_id` bigint NOT NULL COMMENT '钱包编号',
      `biz_type` int NOT NULL COMMENT '关联业务分类',
      `biz_id` varchar(64) NOT NULL COMMENT '关联业务编号',
      `title` varchar(256) NOT NULL COMMENT '流水说明',
      `price` int NOT NULL COMMENT '交易金额，单位分',
      `balance` int NOT NULL COMMENT '交易后余额，单位分',
      `creator` varchar(64) DEFAULT '' COMMENT '创建者',
      `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
      `updater` varchar(64) DEFAULT '' COMMENT '更新者',
      `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
      `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
      `tenant_id` bigint NOT NULL DEFAULT '0',
      PRIMARY KEY (`id`)
) COMMENT='会员钱包流水';